version: 0.1.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
configuration:
- Debug
- Release
- StaticRelease
- StaticDebug
platform:
- x64
- x86
before_build:
- ps: >-
    mkdir C:\sysroot

    mkdir C:\sysroot\bin

    mkdir C:\sysroot\include

    mkdir C:\sysroot\lib

after_build:
- cmd: 7z a .\%APPVEYOR_BUILD_ID%.zip C:\sysroot\*

environment:
  SYSROOT: C:\sysroot\
  INCLUDE: C:\sysroot\include\
  LIBS: C:\sysroot\libs\
build:
  project: win32/libcalendars.sln
  verbosity: minimal
artifacts:
- path: .\*.zip
  type: zip

