version: 0.1.{build}
image:
- Visual Studio 2017
- Visual Studio 2015

configuration:
- Debug
- Release
- StaticRelease
- StaticDebug

platform:
- x64
- x86

before_build:
- ps: >-
    mkdir C:\sysroot

    mkdir C:\sysroot\bin

    mkdir C:\sysroot\include

    mkdir C:\sysroot\lib

environment:
  SYSROOT: C:\sysroot\
  INCLUDE: C:\sysroot\include\
  LIBS: C:\sysroot\libs\

build:
  project: win32/libcalendars.sln
  verbosity: detailed

after_build:
- ps: >-
   $env:BUILD_ARCH = $env:PLATFORM

   switch($env:CONFIGURATION)
        {
        "Debug" {export $env:BUILD_TYPE = "debug-shared"}
        "Release" {export $env:BUILD_TYPE = "release-shared"}
        "StaticDebug" {export $env:BUILD_TYPE = "debug-static"}
        "StaticRelease" {export $env:BUILD_TYPE = "release-static"}
        }

   switch($env:APPVEYOR_BUILD_WORKER_IMAGE)
        {
        "Visual Studio 2017" {export $env:BUILD_MSVC = "msvc14_1"}
        "Visual Studio 2015" {export $env:BUILD_MSVC = "msvc14_1"}
        }

- cmd: 7z a .\%APPVEYOR_PROJECT_NAME%-%BUILD_ARCH%-%BUILD_MSVC%-%BUILD_TYPE%.zip C:\sysroot\*

artifacts:
- path: .\*.zip
  type: zip

