version: 0.1.{build}
image:
- Visual Studio 2017
- Visual Studio 2015

configuration:
- Debug
- Release
- StaticRelease
- StaticDebug

platform:
- x64
- x86

before_build:
- ps: >-
    mkdir C:\sysroot

    mkdir C:\sysroot\bin

    mkdir C:\sysroot\include

    mkdir C:\sysroot\lib

environment:
  SYSROOT: C:\sysroot\
  INCLUDE: C:\sysroot\include\
  LIBS: C:\sysroot\libs\
  matrix:
        - platform: x86
          BUILD_ARCH: win32
        - platform: x64
          BUILD_ARCH: win64
        - configuration: Debug
          BUILD_TYPE: debug-dynamic
        - configuration: Release
          BUILD_TYPE: release-dynamic
        - configuration: StaticRelease
          BUILD_TYPE: release-static
        - configuration: StaticDebug
          BUILD_TYPE: debug-static
        -image: Visual Studio 2017
          BUILD_MSVC: msvc14_1
        -image: Visual Studio 2015
          BUILD_MSVC: msvc14

build:
  project: win32/libcalendars.sln
  verbosity: minimal

after_build:
- cmd: 7z a .\%APPVEYOR_PROJECT_NAME%-%BUILD_ARCH%-%BUILD_MSVC%-%BUILD_TYPE%.zip C:\sysroot\*

artifacts:
- path: .\*.zip
  type: zip

