version: 0.1.{build}
image:
- Visual Studio 2017
        environment:
            BUILD_MSVC: msvc14_1
- Visual Studio 2015
        environment:
            BUILD_MSVC: msvc14

configuration:
- Debug
        environment:
            BUILD_TYPE: debug-dynamic
- Release
        environment:
            BUILD_TYPE: release-dynamic
- StaticRelease
        environment:
            BUILD_TYPE: release-static
- StaticDebug
        environment:
            BUILD_TYPE: debug-static

platform:
- x64
        environment:
            BUILD_ARCH: win64
- x86
        environment:
            BUILD_ARCH: win32

before_build:
- ps: >-
    mkdir C:\sysroot

    mkdir C:\sysroot\bin

    mkdir C:\sysroot\include

    mkdir C:\sysroot\lib

after_build:
- cmd: 7z a .\%APPVEYOR_PROJECT_NAME%-%BUILD_ARCH%-%BUILD_MSVC%-%BUILD_TYPE%.zip C:\sysroot\*

environment:
  SYSROOT: C:\sysroot\
  INCLUDE: C:\sysroot\include\
  LIBS: C:\sysroot\libs\
build:
  project: win32/libcalendars.sln
  verbosity: minimal
artifacts:
- path: .\*.zip
  type: zip

