version: 0.1.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
configuration:
- Debug
- Release
- StaticRelease
- StaticDebug
platform:
- x64
- x86
before_build:
- ps: >-
    mkdir .\sysroot

    mkdir .\sysroot\bin

    mkdir .\sysroot\include

    mkdir .\sysroot\lib

after_build:
- ps: 7z a %APPVEYOR_BUILD_ID%.zip %APPVEYOR_BUILD_FOLDER%\sysroot\*

environment:
  SYSROOT: .\sysroot
  INCLUDE: .\sysroot\include
  LIBS: .\sysroot\libs
build:
  project: win32/libcalendars.sln
  verbosity: minimal
artifacts:
- path: %APPVEYOR_BUILD_ID%.zip
  type: zip

