version: 0.1.{build}
image:
- Visual Studio 2017
- Visual Studio 2015

configuration:
- Debug
- Release
- StaticRelease
- StaticDebug

platform:
- x64
- x86

before_build:
- ps: >-
    mkdir C:\sysroot

    mkdir C:\sysroot\bin

    mkdir C:\sysroot\include

    mkdir C:\sysroot\lib

environment:
  SYSROOT: C:\sysroot\
  INCLUDE: C:\sysroot\include\
  LIBS: C:\sysroot\libs\

matrix:
  - platform: x86
    image: Visual Studio 2017
    configuration: Debug
    environment:
      BUILD_ARCH: win32
      BUILD_TYPE: debug-dynamic
      BUILD_MSVC: msvc14_1
  - platform: x64
    image: Visual Studio 2017
    configuration: Debug
    environment:
      BUILD_ARCH: win64
      BUILD_TYPE: debug-dynamic
      BUILD_MSVC: msvc14_1

build:
  project: win32/libcalendars.sln
  verbosity: minimal

after_build:
- cmd: 7z a .\%APPVEYOR_PROJECT_NAME%-%BUILD_ARCH%-%BUILD_MSVC%-%BUILD_TYPE%.zip C:\sysroot\*

artifacts:
- path: .\*.zip
  type: zip

